### PR TITLE
Made vcpuCount configuration same as memSizeMb

### PR DESCRIPTION
**Pull request by Zyqsempai**
Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>

Issue #359 

*Description of changes:*
Made vcpuCount configuration same as memSizeMb:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Zyqsempai** [comment]
@xibz @nmeyerhans  PTAL

**Comment by xibz** [comment]
@Zyqsempai - Thank you for the PR. Much appreciated! This looks good to me, with one minor comment. In the `config.json.example`, `cpu_count` is still present. Let's remove that. Otherwise this looks good.

**Comment by Zyqsempai** [comment]
@xibz Hi, sorry, currently I am on vacation, without laptop, will be back on 4th January and will fix it. Thanks.

**Comment by Zyqsempai** [comment]
@xibz Done, thank you for waiting!

**Comment by xibz** [comment]
@Zyqsempai - Np, and thank you again for the contribution!

**Pull request merged**
