### PR TITLE
Removed rootfs mounting

### PR DESCRIPTION
**Pull request by Zyqsempai**
Signed-off-by: bpopovschi <zyqsempai@mail.ru>

Issue #271 

Removed container rootfs mounting

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Zyqsempai** [comment]
@sipsma PTAL

**Comment by sipsma** [comment]
Thanks @Zyqsempai ! Looks good but I think there's a few additional small things:
1. We can go ahead and [remove this file too](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/tools/image-builder/files_debootstrap/etc/systemd/system/firecracker.target.wants/container-rootfs.mount)
1. [These lines from the documentation can be removed too](https://github.com/firecracker-microvm/firecracker-containerd/blame/master/tools/image-builder/README.md#L24-L26)
1. There was a single test failure due to the fact that the rootfs size changed by not including that file anymore (you can see it by clicking `Details` next to `buildkite/firecracker-containerd` on this PR). This is just a result of #267 . Until that's resolved, you can just update the size assertion in that test case based on the output of the failure in buildkite.

**Comment by sipsma** [comment]
@nmeyerhans can you take a quick look at this too?

**Comment by nmeyerhans** [comment]
@Zyqsempai Thanks for this. Please address comments from @sipsma, but otherwise, LGTM.

**Comment by Zyqsempai** [comment]
@sipsma Thanks for your comments.
Related to the failing test, the problem is that in test output the data somehow is wrong.
```
-vda 254:0 0 53641216B 0 | 104 115 113 115 128 28 0 0
+vda 254:0 0 53641216B 0 | 104 115 113 115 126 28 0 0
```
the both, actual and expected are the same. Strange.

**Comment by sipsma** [comment]
@Zyqsempai I was very confused at first too and had to stare at it for a long time, but I finally noticed the difference:
-vda 254:0 0 53641216B 0 | 104 115 113 115 **128** 28 0 0
+vda 254:0 0 53641216B 0 | 104 115 113 115 **126** 28 0 0

So I think we just need to change `128` to `126` in the test case for now.

**Comment by sipsma** [comment]
@Zyqsempai This needs a rebase, then we can go ahead and merge

**Comment by Zyqsempai** [comment]
@sipsma Done.

**Comment by sipsma** [comment]
@Zyqsempai I think you accidentally undid some recent commits when doing the rebase, we just need to make sure the changes made here are still applied along with yours:
* https://github.com/firecracker-microvm/firecracker-containerd/commit/75fa787b59c8eb9a4e62ab2a43d1a3ef131df7c4
* https://github.com/firecracker-microvm/firecracker-containerd/commit/1f55138664680c9f4effeabb81e077478f9f70cb

**Comment by Zyqsempai** [comment]
@sipsma Oh, sorry for that, fixed.

**Comment by sipsma** [comment]
@Zyqsempai No worries at all! Appreciate your help on all this

**Pull request merged**
