### PR TITLE
Upgrade to containerd 1.5.2

### PR DESCRIPTION
**Pull request by kzys**
*Issue #, if available:*

*Description of changes:*

This is the combination of #467 and #451. firecracker-containerd's containerd is 1.3.x which is EOL'd. This PR upgrades containerd from 1.3 to 1.5.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by estesp** [comment]
1.5.2 should be out today that updates `runc` based on the CVE just announced.

**Comment by kzys** [comment]
@estesp Thanks! 1.5.2 is out and I've updated the first commit in this pull request.

**Review by estesp — APPROVED** [review]
LGTM (not a maintainer)

**Review by RoyceDavison — APPROVED** [review]
LGTM 🍻

**Pull request merged**
