### PR TITLE
Mount and start Agent instead of calling systemd

### PR DESCRIPTION
**Pull request by kzys**
It won't be suitable for production, but would be interesting to see
the baseline of our performance.

Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kzys** [comment]
```
% make -C runtime benchmark-BenchmarkCreateAndStopVM
make: Entering directory '/home/katokazu/ec2-ws/firecracker-containerd/runtime'
/home/katokazu/ec2-ws/firecracker-containerd/runtime/../tools/thinpool.sh reset ""
docker run --rm -it \
        --privileged \
        --ipc=host \
        --network=none \
        --volume /dev:/dev \
        --volume /run/udev/control:/run/udev/control \
        --volume /home/katokazu/ec2-ws/firecracker-containerd/runtime/logs:/var/log/firecracker-containerd-test \
        --volume /home/katokazu/ec2-ws/firecracker-containerd/runtime/..:/src \
        --volume gocache:/go \
        --env ENABLE_ISOLATED_TESTS=1 \
        --env FICD_DM_VOLUME_GROUP= \
        --env FICD_DM_POOL= \
        --env GOPROXY=direct \
        --env GOSUMDB=off \
        --env NUMBER_OF_VMS= \
        --workdir="/src/runtime" \
        --init \
        localhost/firecracker-containerd-test:latest \
        "go test  -run IGNORE -bench 'BenchmarkCreateAndStopVM'"
goos: linux
goarch: amd64
pkg: github.com/firecracker-microvm/firecracker-containerd/runtime
BenchmarkCreateAndStopVM_Vcpu1_Isolated-96                     1        1699662805 ns/op
BenchmarkCreateAndStopVM_Vcpu5_Isolated-96                     1        1931725184 ns/op
BenchmarkCreateAndStopVM_Quiet_Isolated-96                     1        1462654875 ns/op
BenchmarkCreateAndStopVM_Parallel10_Isolated-96                1        1782024495 ns/op
PASS
ok      github.com/firecracker-microvm/firecracker-containerd/runtime   6.912s
make: Leaving directory '/home/katokazu/ec2-ws/firecracker-containerd/runtime'
```

**Comment by kzys** [comment]
I updated the benchmarks to only measure CreateVM (#430). The change has been merged and then, I rebased this branch.

Here are the numbers:

```
% make -C runtime benchmark-TestPerf_CreateVM EXTRAGOARGS=-v
make: Entering directory '/home/katokazu/ec2-ws/firecracker-containerd/runtime'
/home/katokazu/ec2-ws/firecracker-containerd/runtime/../tools/thinpool.sh reset
""
docker run --rm -it \
        --privileged \
        --ipc=host \
        --network=none \
        --volume /dev:/dev \
        --volume /run/udev/control:/run/udev/control \                         
        --volume /home/katokazu/ec2-ws/firecracker-containerd/runtime/logs:/var/log/firecracker-containerd-test \
        --volume /home/katokazu/ec2-ws/firecracker-containerd/runtime/..:/src \
        --volume gocache:/go \
        --env ENABLE_ISOLATED_TESTS=1 \
        --env FICD_DM_VOLUME_GROUP= \
        --env FICD_DM_POOL= \
        --env GOPROXY=direct \
        --env GOSUMDB=off \
        --env NUMBER_OF_VMS= \
        --workdir="/src/runtime" \
        --init \
        localhost/firecracker-containerd-test:latest \                         
        "go test -v -run 'TestPerf_CreateVM'"                                  
=== RUN   TestPerf_CreateVM
=== RUN   TestPerf_CreateVM/vcpu=1
=== RUN   TestPerf_CreateVM/vcpu=5
=== RUN   TestPerf_CreateVM/firecracker-demo                                   
--- PASS: TestPerf_CreateVM (48.05s)
    --- PASS: TestPerf_CreateVM/vcpu=1 (16.69s)                                
        benchmark_test.go:95: TestPerf_CreateVM/vcpu=1: avg:550.830191ms samples:[552.54699ms 550.41861ms 550.285098ms 550.843866ms 550.504184ms 550.341848ms 551.536961ms 550.822171ms 550.206276ms 550.795915ms]                             
    --- PASS: TestPerf_CreateVM/vcpu=5 (16.70s)                                
        benchmark_test.go:95: TestPerf_CreateVM/vcpu=5: avg:550.909063ms samples:[551.615076ms 550.352049ms 550.55198ms 552.307666ms 550.7902ms 551.17313ms 550.946124ms 549.940938ms 550.215807ms 551.197668ms]                               
    --- PASS: TestPerf_CreateVM/firecracker-demo (14.66s)                      
        benchmark_test.go:95: TestPerf_CreateVM/firecracker-demo: avg:351.040437ms samples:[350.837762ms 350.815218ms 351.527134ms 351.429124ms 350.888522ms 351.072437ms 351.243018ms 350.566482ms 350.857394ms 351.167279ms]                 
PASS
ok      github.com/firecracker-microvm/firecracker-containerd/runtime   48.078s
make: Leaving directory '/home/katokazu/ec2-ws/firecracker-containerd/runtime' 
```

So, stripping down init from systemd to a few shell commands doesn't affect CreateVM's latency.

**Comment by ustiugov** [comment]
@kzys thank you! 

I would like to reproduce this and take a look at the containerd's log. 
Unfortunately, testing process is not documented... I build `test-images` but I get the following error:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/dev/init\": stat /dev/init: no such file or directory": unknown.
```
Could you please help me fix this problem? I can try to document the testing setup afterwards

**Comment by kzys** [comment]
@ustiugov Sorry for the late reply. That's strange. Can you share the full logs?

**Comment by ustiugov** [comment]
@kzys Sorry for the late reply. Here you go:
```
make: Entering directory '/home/ustiugov/go/src/github.com/firecracker-microvm/firecracker-containerd/runtime'
/home/ustiugov/go/src/github.com/firecracker-microvm/firecracker-containerd/runtime/../tools/thinpool.sh reset ""
docker run --rm -it \
        --privileged \
        --ipc=host \
        --network=none \
        --volume /dev:/dev \
        --volume /run/udev/control:/run/udev/control \
        --volume /home/ustiugov/go/src/github.com/firecracker-microvm/firecracker-containerd/runtime/logs:/var/log/firecracker-containerd-test \
        --volume /home/ustiugov/go/src/github.com/firecracker-microvm/firecracker-containerd/runtime/..:/src \
        --volume gocache:/go \
        --env ENABLE_ISOLATED_TESTS=1 \
        --env FICD_DM_VOLUME_GROUP= \
        --env FICD_DM_POOL= \
        --env GOPROXY=direct \
        --env GOSUMDB=off \
        --env NUMBER_OF_VMS= \
        --workdir="/src/runtime" \
        --init \
        localhost/firecracker-containerd-test:latest \
        "go test -v -run 'TestPerf_CreateVM'"
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/dev/init\": stat /dev/init: no such file or directory": unknown.
Makefile:76: recipe for target 'benchmark-TestPerf_CreateVM' failed
make: *** [benchmark-TestPerf_CreateVM] Error 127

```

**Comment by kzys** [comment]
Hmm, what is your Docker version?

**Comment by ustiugov** [comment]
@kzys 
```
Docker version 18.09.7, build 2d0083d
```

**Comment by kzys** [comment]
I found https://github.com/moby/moby/issues/37645. Seems the issue has been fixed. Can you upgrade Docker on your host?

**Comment by ustiugov** [comment]
@kzys Thank you, that solved the Issue, however I face a different error now:

```
ustiugov@iccluster124:~/go/src/github.com/firecracker-microvm/firecracker-containerd$ make -C runtime benchmark-TestPerf_CreateVM EXTRAGOARGS=-v
make: Entering directory '/home/ustiugov/go/src/github.com/firecracker-microvm/firecracker-containerd/runtime'
/home/ustiugov/go/src/github.com/firecracker-microvm/firecracker-containerd/runtime/../tools/thinpool.sh reset ""
docker run --rm -it \
        --privileged \
        --ipc=host \
        --network=none \
        --volume /dev:/dev \
        --volume /run/udev/control:/run/udev/control \
        --volume /home/ustiugov/go/src/github.com/firecracker-microvm/firecracker-containerd/runtime/logs:/var/log/firecracker-containerd-test \
        --volume /home/ustiugov/go/src/github.com/firecracker-microvm/firecracker-containerd/runtime/..:/src \
        --volume gocache:/go \
        --env ENABLE_ISOLATED_TESTS=1 \
        --env FICD_DM_VOLUME_GROUP= \
        --env FICD_DM_POOL= \
        --env GOPROXY=direct \
        --env GOSUMDB=off \
        --env NUMBER_OF_VMS= \
        --workdir="/src/runtime" \
        --init \
        localhost/firecracker-containerd-test:latest \
        "go test -v -run 'TestPerf_CreateVM'"
go: downloading github.com/containernetworking/plugins v0.8.5
go: downloading github.com/firecracker-microvm/firecracker-go-sdk v0.21.0
go: downloading github.com/gofrs/uuid v3.2.0+incompatible
go: downloading github.com/docker/distribution v2.7.1-0.20190205005809-0d3efadf0154+incompatible
go: downloading github.com/gogo/googleapis v1.1.0
build github.com/firecracker-microvm/firecracker-containerd/runtime: cannot load github.com/firecracker-microvm/firecracker-go-sdk: reading github.com/firecracker-microvm/firecracker-go-sdk/go.mod at revision v0.21.0: unknown revision v0.21.0
Makefile:76: recipe for target 'benchmark-TestPerf_CreateVM' failed
make: *** [benchmark-TestPerf_CreateVM] Error 1
```

This is weird because I was able to rebuild all containerd components and also the test images.

**Comment by kzys** [comment]
We pull all images beforehand and run tests with `--network=none`, assuming all Docker images are downloaded already. Can you try `make distclean` and then `make test-images`?

Alternatively, you can run the tests with `--network=host`. You should be able to run the tests without network though.

**Comment by ustiugov** [comment]
@kzys Thank you, distclean did help so that images can be run. However, there is still a problem with running the benchmark. Apparently, createAndStopVM the time out error. I've inserted an error check and here is what I get:

```
ustiugov@iccluster124:~/go/src/github.com/firecracker-microvm/firecracker-containerd$ make -C runtime benchmark-TestPerf_CreateVM EXTRAGOARGS=-v
make: Entering directory '/home/ustiugov/go/src/github.com/firecracker-microvm/firecracker-containerd/runtime'
/home/ustiugov/go/src/github.com/firecracker-microvm/firecracker-containerd/runtime/../tools/thinpool.sh reset ""
docker run --rm -it \
        --privileged \
        --ipc=host \
        --network=none \
        --volume /dev:/dev \
        --volume /run/udev/control:/run/udev/control \
        --volume /home/ustiugov/go/src/github.com/firecracker-microvm/firecracker-containerd/runtime/logs:/var/log/firecracker-containerd-test \
        --volume /home/ustiugov/go/src/github.com/firecracker-microvm/firecracker-containerd/runtime/..:/src \
        --volume gocache:/go \
        --env ENABLE_ISOLATED_TESTS=1 \
        --env FICD_DM_VOLUME_GROUP= \
        --env FICD_DM_POOL= \
        --env GOPROXY=direct \
        --env GOSUMDB=off \
        --env NUMBER_OF_VMS= \
        --workdir="/src/runtime" \
        --init \
        localhost/firecracker-containerd-test:latest \
        "go test -v -run 'TestPerf_CreateVM'"
=== RUN   TestPerf_CreateVM
=== RUN   TestPerf_CreateVM/vcpu=1
=== RUN   TestPerf_CreateVM/vcpu=5
=== RUN   TestPerf_CreateVM/firecracker-demo
--- PASS: TestPerf_CreateVM (15.01s)
    --- PASS: TestPerf_CreateVM/vcpu=1 (5.00s)
        benchmark_test.go:85: TestPerf_CreateVM/vcpu=1: Test, context deadline exceeded
    --- PASS: TestPerf_CreateVM/vcpu=5 (5.00s)
        benchmark_test.go:85: TestPerf_CreateVM/vcpu=5: Test, context deadline exceeded
    --- PASS: TestPerf_CreateVM/firecracker-demo (5.00s)
        benchmark_test.go:85: TestPerf_CreateVM/firecracker-demo: Test, context deadline exceeded
PASS
ok      github.com/firecracker-microvm/firecracker-containerd/runtime   15.055s

```

Is it everything needed for running the tests or am I missing anything?

**Comment by kzys** [comment]
Let me close this PR fist. We can continue the discussion on #410.

**Pull request closed without merging**
