### PR TITLE
Bump github.com/mdlayher/vsock to v1.0.0

### PR DESCRIPTION
**Pull request by mdlayher**
Signed-off-by: Matt Layher <mdlayher@gmail.com>

*Issue #, if available:* n/a

*Description of changes:*

Hi all, I finally tagged v1.0.0 today!

https://github.com/mdlayher/vsock/releases/tag/v1.0.0

The code is much tidier now, but only supports Go 1.12+ as that is the minimum required version for every feature we need from Go's runtime network poller integration. As far as I can tell, your tests use Go 1.13+ so that should be fine.

There is a slight breaking API change to enable future expansion via an optional Config parameter (perhaps for network namespaces, timeouts, etc.) so I've adjusted the code for that.

Thanks all!

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Acknowledged.

### CODE REVIEW

**Comment by mdlayher** [comment]
Interesting, seems like `os.ErrDeadlineExceeded` is required in newer `x/net`. I suspect I don't actually require the newer versions of some x/ dependencies but can investigate more over the next couple of days.

**Comment by mdlayher** [comment]
I was pulling latest x/net in my vsock and socket packages but it seems there hasn't been anything we really need in the latest releases. Trying older versions using a slight patch on top of v1.0.0.

If I can get your CI to pass, I'll eventually tag v1.0.1 with the applicable go.mod changes so that other folks can run older Go without issues too. My intent is to support 1.12+ anyway.

**Comment by mdlayher** [comment]
That seems to have done it! I am going to hold off on tagging v1.0.1 as I investigate a couple of other things but will follow up with you all again once I do. Thank you.

**Comment by mdlayher** [comment]
Another one here. Seems like another EAGAIN type case I should look into handling now that we run all syscalls in non-blocking mode from the start:

```
FAIL: TestMultipleVMs_Isolated (132.03s) | 1s
-- | --
  | service_integ_test.go:262: TestMultipleVMs_Isolated: will run 100 vm's
  | service_integ_test.go:355:
  | Error Trace:	service_integ_test.go:355
  | asm_amd64.s:1357
  | Error:      	Received unexpected error:
  | rpc error: code = Unknown desc = failed to create VM: failed to dial the VM over vsock: non-temporary vsock dial failure: failed to dial "rootfs/firecracker.vsock" within 100ms: dial unix rootfs/firecracker.vsock: connect: resource temporarily unavailable
  | Test:       	TestMultipleVMs_Isolated
  | Messages:   	failed to create vm
  | FAIL
  | exit status 1
  | FAIL	github.com/firecracker-microvm/firecracker-containerd/runtime	132.277s
```

**Comment by mdlayher** [comment]
Thanks for clarifying. AFAICT I am properly handling `EAGAIN` from `connect(2)` but please do reach out if you'd like me to investigate a specific failure further.

**Review by kzys — APPROVED** [review]

**Comment by kzys** [comment]
The tests are all green! Seems TestMultipleVMs_Isolated is still unstable even after #552...

**Review by kzys — APPROVED** [review]

**Comment by mdlayher** [comment]
Thanks again!

**Pull request merged**
