### PR TITLE
Upgrade to containerd 1.6.0 release

### PR DESCRIPTION
**Pull request by henry118**
Signed-off-by: Henry Wang <henwang@amazon.com>

#569 Upgrade containerd to 1.6.0 release. This also upgrade minimum version of golang to 1.16.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by henry118** [comment]
[This ttrpc/protobuf issue](https://github.com/containerd/ttrpc/issues/62) was spotted after upgrading to containerd 1.6.0. We'll have to work around it by regenerating fc-cd protos. This has been addressed by [this commit](https://github.com/firecracker-microvm/firecracker-containerd/pull/575/commits/1606b4b8c18dba10e514b56a4f607ba5a956c3f6).

Now another issue has surfaced which is related to #210. It needs to be addressed before we can migrate to containerd 1.6.0.

**Review by austinvazquez — APPROVED** [review]

**Comment by henry118** [comment]
Fixed #210 by restoring the original logic of the `Connect` routine. 

The original logic is actually the same as containerd 1.5, where the task `pid` is [cached](https://github.com/containerd/containerd/blob/2cbf07562b6bfd7565b72c95110586826bdb9755/runtime/v2/shim.go#L316) by containerd upon a task is created. 

This is essentially the same as querying agent for the task pid.

The integ tests are passing after this change.

**Comment by henry118** [comment]
* Squashed commits; and
* Updated commit message to explain changes in this patch.

**Comment by henry118** [comment]
Is there anything else to be addressed before merging this PR into `containerd-1.6.0` branch?

**Comment by kzys** [comment]
> Is there anything else to be addressed before merging this PR into `containerd-1.6.0` branch?

Please update the AL2 pipeline to fix the test failure.

**Comment by kzys** [comment]
Also is it possible to rebase your branch, instead of having the changes from main. It is hard to see the diff now.

**Comment by henry118** [comment]
1. Updated AL2 test hosts and all tests passed;
2. Edited this PR to target the `main` branch.

**Review by kzys — APPROVED** [review]

**Pull request merged**
