### PR TITLE
Remove snapshotter package

### PR DESCRIPTION
**Pull request by mxpv**
*Issue #, if available:*
https://github.com/firecracker-microvm/firecracker-containerd/issues/318

*Description of changes:*
This removes snapshotter package code from our repo.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kzys** [comment]
The change looks good to me. Would it be helpful to tag current master (0.1.0 or "naive-snapshotter") for accessing naive snapshotter someday/someone? I'm unsure how useful the snapshotter for others though.

**Comment by sipsma** [comment]
The getting started guide and quickstart guides both need updates as they still refer to the naive snapshotter, other than that LGTM

**Comment by mxpv** [comment]
@sipsma There are a couple more tasks I'm planning to do, including updating docs, in follow up PRs (list is here https://github.com/firecracker-microvm/firecracker-containerd/issues/318)

@kzys we can, but I'd rather name it `naive-snapshotter` or something, instead of `0.1.0`, so it won't be confused with release update.

**Comment by sipsma** [comment]
> @sipsma There are a couple more tasks I'm planning to do, including updating docs, in follow up PRs (list is here #318)

I don't see a reason to leave the guides in a broken state (even if it's just temporary) as it's not like deleting the snapshotter code is a time-sensitive emergency. Can we just do the bare minimum in this PR to make sure the guides still work (i.e. don't have references to the naive snapshotter that no longer exists) and then do further cleanup in the follow-up PRs?

**Pull request merged**
